version: '1.0'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: forwarding_agent_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/forwarding_agent_db
    restart: always
  backend:
    image: myap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL_FORWARDING_AGENT: jdbc:postgresql://db:5432/forwarding_agent_db
      DATABASE_USERNAME_FORWARDING_AGENT: postgres
      DATABASE_PASSWORD_FORWARDING_AGENT: 1234
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      JWT_SECRET_PHRASE: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
      IMAGE_STORAGE_FOLDER_FORWARDING_AGENT:
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
volumes:
  database-data: